name: Docker Build Test Push Actions

description: |
  This action builds a Docker image and optionally pushes it to a registry.
  It supports multi-architecture builds and can be used in GitHub Actions workflows.

inputs:
  arch: 
   description: 'The architecture for the build (e.g., amd64, arm64)'
   required: true
  context:
   description: 'The context directory for the Docker build'
   required: true
  dockerfile:
   description: 'Path to the Dockerfile'
   required: true
  tag_prefix:
    description: 'Prefix for the Docker image tag'
    required: true
  push:
    description: 'Whether to push the built image to the registry'
    required: false
    default: 'false'
  github_token:
    description: 'GitHub token for authentication'
    required: false

outputs:
  tag_prefix:
    description: 'The tag prefix used for the Docker image'
    value: ${{ steps.extract.output.tag_prefix }}

runs:
  using: "composite"
  steps:
   - name: Set up QEMU
     uses: docker/setup-qemu-action@v3

   - name: Set up Buildx
     uses: docker/setup-buildx-action@v3

   - name: Login to GHCR
     if: ${{inputs.push == 'true'}}
     uses: docker/login-action@v3
     with:
        registry: ghcr.io
        username: ${{ github.actor }}
        token: ${{ inputs.github_token }}

   - name: Build and optionally push Docker image
     uses: docker/build-push-action@v6
     with:
        context: ${{ inputs.context}}
        dockerfile: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        platforms: linux/${{ inputs.arch }}
        tags: ${{ inputs.tag_prefix }}:${{ inputs.arch }}
        load: ${{ inputs.push != 'true' }}
     
     
