name: payment Build Push

on:
  push:
    paths:
      - 'payment/**'
  pull_request:
    paths:
      - 'payment/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: false
        default: 'master'

jobs:
 
  build-test:
    if: github.ref != 'refs/heads/master' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64] 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: shared
        uses: ./.github/actions/shared-build
        with:
          arch: ${{ matrix.arch }}
          context: payment
          dockerfile: payment/Dockerfile
          tag_prefix: ghcr.io/rajarshigit2441139/robot-shop-payment
          push: "false"
    
  Push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: shared
        uses: ./.github/actions/shared-build
        with:
          arch: ${{ matrix.arch }}
          context: payment
          dockerfile: payment/Dockerfile
          tag_prefix: ghcr.io/rajarshigit2441139/robot-shop-payment
          push: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     